basePath: /api
host: 127.0.0.1:8080
info:
  contact:
    email: support@example.com
    name: API Support
    url: http://www.example.com/support
  description: This is a Boilerplate.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://example.com/terms/
  title: Gin Boilerplate
  version: v1.0.0
paths: {}
swagger: "2.0"
